apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lamtruong1609/devops-proj.git
    targetRevision: main
    path: deploy
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true

