apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: app-gateway
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: nginx
  listeners:
  - name: argo-http
    port: 80
    protocol: HTTP
    hostname: "argo.jasonkube.pilot"
  - name: argo-https
    hostname: "argo.jasonkube.pilot"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: argo-jasonkube-pilot-tls
        kind: Secret
        group: ""

